### ISSUE TITLE
formInput Helper

### ISSUE THREAD

**Issue by N3XT0R** [Lansoweb/LosUi#10]
Hello,

i have a feature-request for your module.
Sometimes it is needed to have Input-Fields without a label. At Example: Search-Fields.

Normally zf2 have a view helper called "formInput" for it. It would be great when you would implement it too.

**Comment by Lansoweb** [comment]
Hi @N3XT0R, sorry for the delay. Actually, the current losFormRow handles inputs without labels, just do not define it:

``` php
   /**
     * @ORM\Column(type="string")
     * @Form\Filter({"name":"StringTrim"})
     * @Form\Validator({"name":"StringLength", "options":{"min":3, "max":250}})
     * @Form\Attributes({"type":"text","placeholder":"Search"})
     * @Form\Options({"label":"Search"})
     */
    protected $search;
```

Will generate the label, so just remove the label:

``` php
   /**
     * @ORM\Column(type="string")
     * @Form\Filter({"name":"StringTrim"})
     * @Form\Validator({"name":"StringLength", "options":{"min":3, "max":250}})
     * @Form\Attributes({"type":"text","placeholder":"Search"})
     */
    protected $search;
```
