### ISSUE TITLE
[Feature-Request] DateSelect decoration

### ISSUE THREAD

**Issue by N3XT0R** [Lansoweb/LosUi#11]
Hello,

at first, nice work again. But one thing is missing inside your module :/.
DateSelect FormElement ist not implemented sadly. Maybe you could implement it in style of thee Select FormElements, too ?

**Comment by Lansoweb** [comment]
@N3XT0R You are right. We have the "date" tag in html5, but unfortunately it's not yet implemented in some browsers (just tested on Safari and FF). Will implement this feature. Thanks!

**Comment by N3XT0R** [comment]
@Lansoweb DateSelect ist not a Date field. The Parent-Class of DateSelect is MonthSelect and in DateSelect are three SelectElements.

**Comment by Lansoweb** [comment]
@N3XT0R True. Will implement this as soon as possible. Thanks.

**Comment by Lansoweb** [comment]
@N3XT0R Done at 1.0.25. Thanks!
