### ISSUE TITLE
Display FA Icons

### ISSUE THREAD

**Issue by N3XT0R** [Lansoweb/LosUi#2]
Hello,

first. i don't have a bug, only an idea. I saw that you uses "span" elements for icons. Some themes are using the "i" element for fontawesome icons. It would be awesome when it would be possible to choose theelement-tag i or span.

**Comment by Lansoweb** [comment]
@N3XT0R Nice suggestion. Will include it in the next release. Thanks!

**Comment by Lansoweb** [comment]
Done in version 1.0.16. Check the README for usage. thanks.
