### ISSUE TITLE
Bug in Menu

### ISSUE THREAD

**Issue by angelov-todor** [Lansoweb/LosUi#4]
I am pretty sure that you meant !empty

https://github.com/Lansoweb/LosUi/blob/master/src/LosUi/View/Helper/Navigation/Menu.php#L91

**Comment by Lansoweb** [comment]
You're right! Fixed in https://github.com/Lansoweb/LosUi/commit/41870fc0f96a49d728db528576e1cdf9e957a38b and will generate a new release soon. Thanks again!
