### ISSUE TITLE
Utilize Zend Form Fieldset And Collections

### ISSUE THREAD

**Issue by angelov-todor** [Lansoweb/LosUi#5]
Hi, thanks for the great work. It would be nice if you utilize fully zend form element collection and fieldset, 
as for now the hidden template is not being rendered and there is no wrapping option.

**Comment by Lansoweb** [comment]
@angelov-todor Hi! Thanks for the support! Sorry, i don't quite understand, could you elaborate?

**Comment by angelov-todor** [comment]
Sorry, wrong repository. I am kind of testing couple of BS3 -> ZF2 implementations.
