### ISSUE TITLE
losFormRow - automatic label showing

### ISSUE THREAD

**Issue by N3XT0R** [Lansoweb/LosUi#6]
Hello,
i have a suggestion for the View-Helper "losFormRow". Maybe it should be a parameter available for "activating" or "deactivating" of form label auto display, or it should be implemented a new form helper for constructs like this:

```
<div class="form-group">
        <label for="suffix" class="col-md-3 control-label">Suffix</label>
        <div class="col-md-9">
            <div class="input-group input-group-sm">
                <span class="input-group-addon">main_</span>
                <input type="text" name="suffix" id="suffix" class="form-control input-sm">
            </div>
        </div>
    </div>
```

**Comment by Lansoweb** [comment]
Hi @N3XT0R ! I just updated the module with the addon feature (issue #9). Will release the 1.0.20.
