### ISSUE TITLE
Form buttons

### ISSUE THREAD

**Issue by angelov-todor** [Lansoweb/LosUi#8]
https://github.com/Lansoweb/LosUi/blob/master/src/LosUi/Form/View/Helper/Form.php#L58

perhaps the check can be made with Submit too...

  if ($element instanceof Button || $element instanceof \Zend\Form\Element\Submit)

**Comment by Lansoweb** [comment]
@angelov-todor You're right! Will update the code today. Thanks again!

**Comment by Lansoweb** [comment]
Fixed on 1.0.19.

**Comment by angelov-todor** [comment]
Tnanks.
